version: "3"

services:
    postgresql:
        image: "postgres:latest"
        container_name: postgres
        restart: always
        environment:
          POSTGRES_PASSWORD: 123
          POSTGRES_USER: root
          POSTGRES_DB: checkout
          PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
    db-data:
